# Generated by Django 5.0.3 on 2024-03-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mediaalbum_photo_album_video_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='video',
            name='album',
        ),
        migrations.DeleteModel(
            name='MediaAlbum',
        ),
    ]
