# Generated by Django 5.0.3 on 2024-03-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_album_photo_album_video_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
